# Generated by Django 4.2.6 on 2023-12-10 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_customer_alter_manager_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="name",
        ),
    ]
