# Generated by Django 4.2.6 on 2023-12-10 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_customer_name_remove_manager_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["comment_date"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["username"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["date"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="manager",
            options={
                "ordering": ["username"],
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ["score"],
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["event", "name"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketpurchase",
            options={
                "ordering": ["ticket_name", "buyer", "date"],
                "verbose_name": "Ticket Purchase",
                "verbose_name_plural": "Ticket Purchases",
            },
        ),
    ]
