# Generated by Django 4.2.6 on 2023-12-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_customer_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketpurchase",
            name="code",
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
