# Generated by Django 4.2.6 on 2023-12-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_ticketpurchase_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketpurchase",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="core.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="ticket_name",
            field=models.CharField(max_length=255),
        ),
    ]
