# Generated by Django 4.2.6 on 2023-12-10 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_ticketpurchase_ticket_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="buyers",
        ),
    ]
