# Generated by Django 4.2.6 on 2023-12-11 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_ticket_buyers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
