# Generated by Django 4.2.6 on 2023-12-12 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketpurchase",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
