# Generated by Django 4.2.6 on 2023-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_ticketpurchase_buyer_delete_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
